#!/usr/bin/env bash
_DIR="$(dirname $0)"
export CLICKHOUSE_IMAGE=${CLICKHOUSE_IMAGE:="$(awk -F '[ :]' '{print $2}' $_DIR/Dockerfile)"}
export CLICKHOUSE_IMAGE_VERSION=${CLICKHOUSE_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' $_DIR/Dockerfile)"}
export CLICKHOUSE_ROOT=${CLICKHOUSE_ROOT:="$DOKKU_LIB_ROOT/services/clickhouse"}
export CLICKHOUSE_HOST_ROOT=${CLICKHOUSE_HOST_ROOT:=$CLICKHOUSE_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "export" "import")
export PLUGIN_COMMAND_PREFIX="clickhouse"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$CLICKHOUSE_ROOT
export PLUGIN_DATA_HOST_ROOT=$CLICKHOUSE_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(9000 8123)
export PLUGIN_DATASTORE_WAIT_PORT=9000
export PLUGIN_DEFAULT_ALIAS="CLICKHOUSE"
export PLUGIN_DISABLE_PULL=${CLICKHOUSE_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="CLICKHOUSE_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_CLICKHOUSE"
export PLUGIN_IMAGE=$CLICKHOUSE_IMAGE
export PLUGIN_IMAGE_VERSION=$CLICKHOUSE_IMAGE_VERSION
export PLUGIN_SCHEME="clickhouse"
export PLUGIN_SERVICE="Clickhouse"
export PLUGIN_VARIABLE="CLICKHOUSE"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="config"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.31.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.3.3"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.10.3"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.4.3"
